# Generated by Django 6.0.6 on 2026-07-06 03:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('withdraw_fee_fixed', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_label', models.CharField(max_length=30, unique=True)),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Revenu plateforme (compte bloqué)',
                'verbose_name_plural': 'Revenus plateforme (compte bloqué)',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moncash_withdraw_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('2.50'), help_text='Frais appliqués sur les retraits HTG vers MonCash (%)', max_digits=5)),
                ('moncash_deposit_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Frais appliqués sur les dépôts HTG via MonCash (%), 0 = gratuit', max_digits=5)),
                ('auto_process_withdrawals', models.BooleanField(default=True, help_text="Si activé, les retraits HTG et crypto sont envoyés automatiquement sans validation manuelle d'un administrateur. ATTENTION : irréversible en cas de fraude.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réglages du site',
                'verbose_name_plural': 'Réglages du site',
            },
        ),
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('conversion_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('withdraw_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('withdraw_fee_fixed', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text="Frais fixe de retrait, dans l'unité de cette devise (ex: 2 pour 2 USDT)", max_digits=20)),
                ('min_withdraw_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text="Montant minimum de retrait autorisé, dans l'unité de cette devise", max_digits=20)),
                ('htg_exchange_rate', models.DecimalField(decimal_places=4, help_text='1 unité de cette crypto = X HTG', max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currencies', to='wallets.cryptonetwork')),
            ],
        ),
        migrations.CreateModel(
            name='HTGWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='htg_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('deposit_address', models.CharField(blank=True, max_length=255)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallets.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DEPOSIT_HTG', 'Dépôt MonCash'), ('WITHDRAW_HTG', 'Retrait MonCash'), ('DEPOSIT_CRYPTO', 'Dépôt Crypto'), ('WITHDRAW_CRYPTO', 'Retrait Crypto'), ('CONVERT_HTG_TO_CRYPTO', 'Achat Crypto (HTG → Crypto)'), ('CONVERT_CRYPTO_TO_HTG', 'Vente Crypto (Crypto → HTG)'), ('CONVERT', 'Conversion')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En traitement'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('currency_label', models.CharField(max_length=30)),
                ('destination_address', models.CharField(blank=True, max_length=255)),
                ('moncash_reference', models.CharField(blank=True, max_length=100)),
                ('provider_payment_id', models.CharField(blank=True, max_length=150)),
                ('hidden_by_user', models.BooleanField(default=False)),
                ('admin_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'hidden_by_user'], name='wallets_tra_user_id_a7bc5c_idx')],
            },
        ),
    ]
